"""
Vercel Serverless API - AI Employee Platinum Tier

This provides serverless endpoints for the Cloud Agent on Vercel.
Endpoints:
- /api/health - Health check
- /api/process - Trigger processing
- /api/status - Agent status
- /webhook/email - Email webhook
- /webhook/social - Social media webhook

Note: Vercel serverless functions have timeout limits.
For continuous operation, deploy Cloud Agent on a Cloud VM instead.
"""

import json
import logging
import os
import sys
from datetime import datetime
from pathlib import Path
from typing import Dict, Any

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger('vercel_api')


def get_vault_path() -> Path:
    """Get vault path from environment or use temp directory."""
    vault_path = os.environ.get('VAULT_PATH', '/tmp/ai-employee-vault')
    return Path(vault_path)


def ensure_vault_structure():
    """Ensure vault directory structure exists."""
    vault_path = get_vault_path()
    
    folders = [
        'Needs_Action/Cloud',
        'Needs_Action/Local',
        'In_Progress/Cloud',
        'In_Progress/Local',
        'Pending_Approval/Cloud',
        'Pending_Approval/Local',
        'Updates',
        'Signals',
        'Done',
        'Logs',
    ]
    
    for folder in folders:
        (vault_path / folder).mkdir(parents=True, exist_ok=True)


def lambda_handler(event: Dict[str, Any], context: Any) -> Dict[str, Any]:
    """
    AWS Lambda-style handler (for compatibility).
    """
    return handle_request(event)


def handle_request(event: Dict[str, Any]) -> Dict[str, Any]:
    """
    Handle incoming HTTP request.
    
    Returns Vercel/Netlify compatible response.
    """
    ensure_vault_structure()
    
    path = event.get('path', '/')
    method = event.get('httpMethod', 'GET')
    body = event.get('body', '{}')
    
    logger.info(f"Request: {method} {path}")
    
    try:
        if path == '/api/health' or path == '/health':
            return health_check()
        
        elif path == '/api/process':
            if method == 'POST':
                return trigger_processing(json.loads(body) if body else {})
            return error_response('Method not allowed', 405)
        
        elif path == '/api/status':
            return get_status()
        
        elif path.startswith('/webhook/'):
            webhook_type = path.split('/webhook/')[1]
            return handle_webhook(webhook_type, json.loads(body) if body else {})
        
        else:
            return error_response('Not found', 404)
            
    except Exception as e:
        logger.error(f"Error handling request: {e}", exc_info=True)
        return error_response(str(e), 500)


def health_check() -> Dict[str, Any]:
    """Health check endpoint."""
    vault_path = get_vault_path()
    
    health_data = {
        'status': 'healthy',
        'timestamp': datetime.now().isoformat(),
        'version': '1.0.0-platinum',
        'vault_path': str(vault_path),
        'vault_exists': vault_path.exists(),
        'mode': os.environ.get('AGENT_MODE', 'cloud'),
        'region': os.environ.get('VERCEL_REGION', 'unknown'),
    }
    
    # Check vault folders
    required_folders = ['Needs_Action/Cloud', 'Updates', 'Signals']
    missing_folders = []
    
    for folder in required_folders:
        if not (vault_path / folder).exists():
            missing_folders.append(folder)
    
    if missing_folders:
        health_data['status'] = 'degraded'
        health_data['missing_folders'] = missing_folders
    
    return {
        'statusCode': 200,
        'headers': {
            'Content-Type': 'application/json',
            'Cache-Control': 'no-cache',
        },
        'body': json.dumps(health_data, indent=2),
    }


def trigger_processing(data: Dict) -> Dict[str, Any]:
    """Trigger Cloud Agent processing."""
    vault_path = get_vault_path()
    
    # Create a processing request file
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    request_file = vault_path / 'Needs_Action' / 'Cloud' / f'API_REQUEST_{timestamp}.md'
    
    content = f"""---
type: api_request
source: vercel_api
created: {datetime.now().isoformat()}
---

# API Processing Request

## Request Data
```json
{json.dumps(data, indent=2)}
```

## Instructions
Process this request and write results to /Updates/ folder.

---
*Generated by Vercel API*
"""
    
    request_file.write_text(content, encoding='utf-8')
    
    return {
        'statusCode': 202,
        'headers': {
            'Content-Type': 'application/json',
        },
        'body': json.dumps({
            'status': 'accepted',
            'request_file': request_file.name,
            'message': 'Processing request queued. Results will be available in /Updates/ folder.',
            'timestamp': datetime.now().isoformat(),
        }),
    }


def get_status() -> Dict[str, Any]:
    """Get agent status."""
    vault_path = get_vault_path()
    
    # Count items in each folder
    def count_md(folder: str) -> int:
        path = vault_path / folder
        if not path.exists():
            return 0
        return len([f for f in path.glob('*.md')])
    
    status_data = {
        'timestamp': datetime.now().isoformat(),
        'mode': os.environ.get('AGENT_MODE', 'cloud'),
        'queue': {
            'needs_action_cloud': count_md('Needs_Action/Cloud'),
            'needs_action_local': count_md('Needs_Action/Local'),
            'in_progress_cloud': count_md('In_Progress/Cloud'),
            'pending_approval_cloud': count_md('Pending_Approval/Cloud'),
            'updates': count_md('Updates'),
            'signals': count_md('Signals'),
        },
        'last_activity': get_last_activity(),
    }
    
    return {
        'statusCode': 200,
        'headers': {
            'Content-Type': 'application/json',
        },
        'body': json.dumps(status_data, indent=2),
    }


def get_last_activity() -> str:
    """Get timestamp of last activity."""
    vault_path = get_vault_path()
    logs_dir = vault_path / 'Logs'
    
    if not logs_dir.exists():
        return 'No activity'
    
    # Find most recent log file
    log_files = sorted(logs_dir.glob('*.log'), key=lambda f: f.stat().st_mtime, reverse=True)
    
    if log_files:
        try:
            mtime = datetime.fromtimestamp(log_files[0].stat().st_mtime)
            return mtime.isoformat()
        except Exception:
            return 'Unknown'
    
    return 'No activity'


def handle_webhook(webhook_type: str, data: Dict) -> Dict[str, Any]:
    """Handle incoming webhook."""
    vault_path = get_vault_path()
    
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    
    if webhook_type == 'email':
        # Email webhook (e.g., from SendGrid, Mailgun)
        filename = f'WEBHOOK_EMAIL_{timestamp}.md'
        folder = 'Needs_Action/Cloud'
        
    elif webhook_type == 'social':
        # Social media webhook (e.g., from Twitter, Facebook)
        filename = f'WEBHOOK_SOCIAL_{timestamp}.md'
        folder = 'Needs_Action/Cloud'
        
    else:
        return error_response(f'Unknown webhook type: {webhook_type}', 400)
    
    # Create webhook file
    filepath = vault_path / folder / filename
    
    content = f"""---
type: webhook
webhook_type: {webhook_type}
source: vercel_api
created: {datetime.now().isoformat()}
---

# Webhook: {webhook_type.title()}

## Payload
```json
{json.dumps(data, indent=2)}
```

## Instructions
Process this webhook and take appropriate action.

---
*Generated by Vercel API Webhook*
"""
    
    filepath.write_text(content, encoding='utf-8')
    
    return {
        'statusCode': 202,
        'headers': {
            'Content-Type': 'application/json',
        },
        'body': json.dumps({
            'status': 'received',
            'webhook_type': webhook_type,
            'file': filename,
            'timestamp': datetime.now().isoformat(),
        }),
    }


def error_response(message: str, status_code: int) -> Dict[str, Any]:
    """Create error response."""
    return {
        'statusCode': status_code,
        'headers': {
            'Content-Type': 'application/json',
        },
        'body': json.dumps({
            'error': message,
            'timestamp': datetime.now().isoformat(),
        }),
    }


# Vercel-specific handler
def GET(request):
    """Handle GET requests."""
    path = request.url.path
    
    if path == '/health' or path == '/api/health':
        response = health_check()
    elif path == '/api/status':
        response = get_status()
    else:
        response = error_response('Not found', 404)
    
    return Response(
        body=response['body'],
        status=response['statusCode'],
        headers=response['headers']
    )


def POST(request):
    """Handle POST requests."""
    path = request.url.path
    body = request.body or '{}'
    
    if path == '/api/process':
        response = trigger_processing(json.loads(body))
    elif path.startswith('/webhook/'):
        webhook_type = path.split('/webhook/')[1]
        response = handle_webhook(webhook_type, json.loads(body))
    else:
        response = error_response('Not found', 404)
    
    return Response(
        body=response['body'],
        status=response['statusCode'],
        headers=response['headers']
    )


# Simple Response class for Vercel
class Response:
    def __init__(self, body: str, status: int = 200, headers: Dict = None):
        self.body = body
        self.status = status
        self.headers = headers or {}
